/*
 * File: app/view/Register.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bma.view.Register', {
    extend: 'Ext.form.Panel',

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                title: 'Register',
                items: [
                    {
                        xtype: 'button',
                        itemId: 'loginButton',
                        text: 'Login'
                    }
                ]
            },
            {
                xtype: 'textfield',
                label: 'Username',
                name: 'username'
            },
            {
                xtype: 'emailfield',
                label: 'Email',
                name: 'email',
                placeHolder: 'email@example.com'
            },
            {
                xtype: 'passwordfield',
                label: 'Password',
                name: 'password'
            },
            {
                xtype: 'button',
                itemId: 'registerSubmit',
                ui: 'confirm',
                text: 'Submit'
            }
        ],
        listeners: [
            {
                fn: 'onLoginButtonTap',
                event: 'tap',
                delegate: '#loginButton'
            },
            {
                fn: 'onRegisterSubmitTap',
                event: 'tap',
                delegate: '#registerSubmit'
            }
        ]
    },

    onLoginButtonTap: function(button, e, options) {
        console.log("Button hit: go to login");
        Ext.Viewport.setActiveItem(Ext.create('bma.view.Main'));
    },

    onRegisterSubmitTap: function(button, e, options) {
        var values = this.getValues();
        if (values.username && values.password && values.email) {

            Ext.io.Io.getCurrentGroup({
                success: function(group) {
                    console.log("got group");

                    group.register({
                        params: {
                            username: values.username,
                            password: values.password,
                            email: values.email
                        },
                        success: function() {
                            console.log("success registering");

                            Ext.Viewport.setActiveItem(Ext.create('bma.view.Lobby'));
                        }
                    });
                }
            });
        }
    }

});