/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.Loader.setConfig({
    enabled: true
});

Ext.application({
    models: [
        'Lobby'
    ],
    views: [
        'Main',
        'Register',
        'Lobby'
    ],
    name: 'bma',
    controllers: [
        'Lobby',
        'Main',
        'Register'
    ],

    launch: function() {
        /*Ext.io.Io.setup({
        logLevel: "debug",
        appId: "6tdNQjk8vV2QuOQh9zLK0WTe4h0",
        appSecret: "LeCOKeSPYQYeD7zk",
        url: "http://msg.sencha-dev.io:80"
        });*/
        Ext.io.Io.setup({
            logLevel: "debug",
            appId: "2AWPls2mskX6TvdeuMciYjKfx7j",
            appSecret: "o0tdBG36rlXyMt2K"
        });
        Ext.io.Io.init();
        Ext.create('bma.view.Main', {fullscreen: true});
    }

});
