/*
 * File: app/controller/Lobby.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bma.controller.Lobby', {
    extend: 'Ext.app.Controller',
    config: {
        views: [
            'Lobby'
        ],

        refs: {
            messageList: '#messageList'
        }
    },

    launch: function() {
        var _this = this;

        Ext.io.Io.getCurrentUser({
            success: function(user) {
                _this.user = user;

                messageStore = Ext.create('bma.store.Lobby', {storeId: 'lobbyStore'});
                messageStore.load();
                _this.getMessageList().setStore(messageStore);
                messageStore.sync(function() {
                    console.log('Initial sync ran: lobbyStore');
                });

                user.receive({
                    callback: function(callback, bool, sender, message) {
                        var userId = sender.getUserId();
                        console.log("user got a message!", arguments, userId);

                        var record = {
                            message: message,
                            userID: userId,
                            from: userId,
                            date: new Date().getTime()
                        };
                        console.log("saving message", record);

                        messageStore.add(record);
                        messageStore.sync();
                    }
                });
            }
        });
    }

});