/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.0.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('bma.controller.Main', {
    extend: 'Ext.app.Controller',
    config: {
    },

    init: function(application) {
        Ext.io.Io.getCurrentUser({
            success: function(user) {
                if(user) {
                    Ext.Viewport.setActiveItem(Ext.create('bma.view.Lobby'));
                };
            }
        });
    }

});